### ISSUE TITLE
Histograms don't always reflect amount of logs

### ISSUE THREAD

**Issue by mightyguava** [cashapp/logquacious#100]
I haven't tested this thoroughly, but sometimes the histogram doesn't go back as far as the logs go. Or on occasion the bar lengths don't match the numbers. I've heard a few people say they don't trust the histogram due to seeing inconsistencies themselves.

**Comment by gak** [comment]
Might be related to #89

**Comment by gak** [comment]
I've made a bunch of fixes in #114 that might be related. 

Your report sounds like #89, but let me know if it still happens.
