### ISSUE TITLE
Add HTML escaping for log content

### ISSUE THREAD

**Issue by adrw** [cashapp/logquacious#6]
Log content that contains HTML, CSS, or Javascript currently is rendered/executed and is an XSS attack vector and a CSS nuisance.

Fixing should be done with a trusted library
- [Lodash.escape](https://lodash.com/docs/4.17.15#escape): basic escaping
- [he](https://github.com/mathiasbynens/he): much more robust library that can handle additional escaping parameters

How to escape
- https://wonko.com/post/html-escaping/ (tldr; escape most symbols, not just `<, >, "`)

**Comment by gak** [comment]
Ended up using `he`, thanks @adrw
